README.md: fix Usage example so that it works
... out of the box.  The previously accessed fields were not available
in the objects being accessed:
```
Traceback (most recent call last):
  File "/tmp/xxx.py", line 15, in <module>
    flaw.summary
AttributeError: 'OsidbApiV1FlawsRetrieveResponse200' object has no attribute 'summary'

Traceback (most recent call last):
  File "/tmp/xxx.py", line 20, in <module>
    flaw_dict["summary"]
    ~~~~~~~~~^^^^^^^^^^^
KeyError: 'summary'

Traceback (most recent call last):
  File "/tmp/xxx.py", line 24, in <module>
    all_flaws = osidb_session.flaw.retrieve_list()
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'flaw'. Did you mean: 'flaws'?
```